# 项目相关配置
yk:
  #名称
  name: blog
  #版本
  version: 1.0
  #版权年份
  copyrightYear: 2019
server:
  port: 8080
  ##项目名字配置
  #servlet :
  #  context-path : /demo
  tomcat:
    max-threads: 128
    min-spare-threads: 5
    uri-encoding: UTF-8
    #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
spring :
  # 环境 dev 开发|test 测试|prod生产
  profiles :
    active : dev
  servlet:
    multipart:
      max-request-size: 100MB
      maxFileSize : 10MB
      #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false #开发时关闭缓存,不然没法看到实时页面
    # 资源信息
    messages:
      # 国际化资源文件路径
      basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis : #mybatis 配置
  mapperLocations : classpath*:mybatis/*/*.xml
  executor-type : reuse
  type-aliases-package : com.*.model
  configuration :
    map-underscore-to-camel-case : true
    #控制台打印sql
    log-impl : org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
